aws:
  s3:
    mock: false

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-favxqftapd-stack-awsebrdsdatabase-3acypecswfv9.cfseizkjgpr2.us-east-1.rds.amazonaws.com:5432/ebdb
    username: amigoscode
    password: password